spring:
  datasource:
    url: jdbc:mysql://192.168.174.125:3306/jpa
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
#    更新或者创建数据表结构
      ddl-auto: update
#      naming:
#        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy 默认就是这个，这个是遇到大写字母变小写字母加”_”的命名
#      控制台显示sql
    show-sql: true