server:
 port: 3344

spring:
 application:
   name: microservicecloud-config
 cloud:
  config:
    server:
     git:
      uri: https://github.com/1271845364/microservicecloud-config.git     #GitHub上仓库的名字